version: "3"

services:
  db:
    image: postgres:12
    environment:
      - POSTGRES_DB=modish-inventory
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      
    
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./src:/app/src
      - /usr/app/src/node_modules
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - POSTGRES_DB=modish-inventory
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db

