version: "3.8"

services:
  db:
    container_name: db
    image: postgres:13-alpine
    # restart: always
    ports:
      - '5432:5432'
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - web
  

  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./src:/app/src
      - /usr/app/node_modules
    ports:
      - '3001:3001'
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - web


  # pgadmin4:
  #   container_name: pgadmin4
  #   links:
  #     - db
  #   image: dpage/pgadmin4
  #   restart: always
  #   env_file:
  #     - .env
  #   ports:
  #     - '8080:80'
  #   volumes:
  #     - /data/pgadmin:/root/.pgadmin
  #   depends_on:
  #     - db
  #   networks:
  #     - web

volumes:
   postgres:
      name: nest-modish-docker-db

networks:
  web:
    driver: bridge

